name: Maven CI with Selenium and Cucumber

on:
  push:
    branches:
      - main  # Déclenche l'action sur les push vers la branche main
  pull_request:
    branches:
      - main  # Déclenche l'action sur les pull requests vers la branche main

jobs:
  build:
    runs-on: ubuntu-latest  # Exécute les jobs sur la dernière version d'Ubuntu

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Récupère le code du dépôt

      - name: Set up JDK 17
        uses: actions/setup-java@v3  # Configure l'environnement Java JDK 17
        with:
          java-version: '17'
          distribution: 'adopt'  # Utilise AdoptOpenJDK

      - name: Cache Maven packages
        uses: actions/cache@v3  # Met en cache les dépendances Maven pour accélérer les builds
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}  # Clé de cache basée sur le système d'exploitation et le contenu de pom.xml
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install dependencies
        run: mvn install -DskipTests  # Installe les dépendances sans exécuter les tests

      - name: Run tests
        run: mvn test  # Exécute les tests unitaires

      - name: Generate Cucumber report
        run: mvn verify  # Génère les rapports Cucumber

      - name: Upload test results
        if: always()  # Exécute cette étape quel que soit le résultat des étapes précédentes
        uses: actions/upload-artifact@v3  # Télécharge les résultats des tests
        with:
          name: test-results
          path: target/

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Nécessite que le job 'build' soit terminé

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build project
        run: mvn install -DskipTests  # Construit le projet sans exécuter les tests

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3  # Déploie les rapports sur GitHub Pages
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: target/
